apiVersion: apps/v1
kind: Deployment
metadata: 
  name: test-daemonset
  namespace: prom
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: test-daemonset
  template:
    metadata:
      labels:
        instance: test-daemonset
    spec:
      containers:
      - name: test
        image: cxinsect/prom:v0.0.1
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c","./prom_exporter --config.file /etc/config/prom-exporter.yaml --label-ip $HOSTIP"]
        securityContext:
          privileged: true
        ports:
        - name: metrics
          containerPort: 8888
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/config
          name: test-configmap
        - mountPath: /sys/kernel/debug
          name: kernel
        - mountPath: /lib/modules/
          name: modules
        - mountPath: /usr/src/kernels
          name: users
        env:
        - name: HOSTIP
          valueFrom: 
            fieldRef:
              fieldPath: status.hostIP
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: test-configmap
          name: test-configmap
        - hostPath:
            path: /sys/kernel/debug
            type: Directory
          name: kernel
        - hostPath:
            path: /lib/modules
            type: Directory
          name: modules
        - hostPath:
            path: /usr/src/kernels
            type: Directory
          name: users

      
