image:
  repository: cxinsect/prom
  tag: v0.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8888

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

configMapFile: {}