apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: {{ .Release.Name }}-daemonset
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash","-c"]
        args: ["-c","./prom_exporter --config.file /etc/config/prom-exporter.yaml --label-ip $HOSTIP"]
        securityContext:
          privileged: true
        ports:
        - name: metrics
          containerPort: 8888
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/config
          name: {{ .Release.Name }}-configmap
        - mountPath: /sys/kernel/debug
          name: kernel
        - mountPath: /lib/modules/
          name: modules
        - mountPath: /usr/src/kernels
          name: users
        env:
        - name: HOSTIP
          valueFrom: 
            fieldRef:
              fieldPath: status.hostIP
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-configmap
          name: {{ .Release.Name }}-configmap
        - hostPath:
            path: /sys/kernel/debug
            type: Directory
          name: kernel
        - hostPath:
            path: /lib/modules
            type: Directory
          name: modules
        - hostPath:
            path: /usr/src/kernels
            type: Directory
          name: users

      