apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitor
  namespace: monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      instance: prom-service
  endpoints:
  - port: web
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
 